export enum UserActionTypes {
	USER_AUTH_REQUEST = 'USER_LOGIN_REQUEST',
	USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
	USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS',
	USER_AUTH_FAIL = 'USER_LOGIN_FAIL',
	USER_LOGOT = 'USER_LOGOT',
}
